### ISSUE TITLE
Page selection does not work on website demo

### ISSUE THREAD

**Issue by flora8984461** [material-table-core/website#14]
The page selection works fine when I build my local app, but for some reason it's not working on the website.
for example,
https://material-table-core.com/demos/remote-data/basic

**Comment by matthewoestreich** [comment]
Are you referring to the menu on the left hand side? I'm not sure what you mean by page selection since the page loads fine for me?

**Comment by flora8984461** [comment]
@oze4 Hi, thanks for your reply. Sorry for my unclarity. It's the page selection in the demo of material table. It works fine when I use material-table as library, but seems no reaction on the demo.

**Comment by matthewoestreich** [comment]
Can u maybe create a screen recording of it?

**Comment by flora8984461** [comment]
@oze4 

For sure. Sorry I am outside without my computer right now, I used my phone record this. And it's not working on my computer either.

https://user-images.githubusercontent.com/39588094/127758540-b5996277-7fc4-4596-89d8-a6873e309876.MOV

**Comment by matthewoestreich** [comment]
Ohh that page selection. My fault I misunderstood. 

That's odd. We just made some changes that shouldn't have caused any issues like this - you confirmed this isn't happening locally? Which version are you on?

**Comment by flora8984461** [comment]
> Ohh that page selection. My fault I misunderstood. 
> 
> 
> 
> That's odd. We just made some changes that shouldn't have caused any issues like this - you confirmed this isn't happening locally? Which version are you on?

Yeah, it is working locally when I directly use material-table, not using the demo site. The version I think it's the latest one as of now. I will double check it later. 

Thanks!

**Comment by matthewoestreich** [comment]
Hey @Domino987 we are getting the `onPageChange` is not a func error on the website. I saw another issue for that but we are using `@material-ui/core v4.11.2` - do you remember the fix for it?

Everything works fine when I test locally, so it appears to be related just to the website.

**Comment by matthewoestreich** [comment]
Hey @flora8984461 I was able to get this resolved (had to upgrade `@material-ui/core` to `v4.11.4`.

Thank you for this!

**Comment by Domino987** [comment]
Yes they change the prop name and we changed it with version 3 I think as well.
