### ISSUE TITLE
Confusing link to mbrn/material-table title in app bar

### ISSUE THREAD

**Issue by johnthagen** [material-table-core/website#17]
The link in the top right is still `mbrn/material-table` confused me at first because it linked to the *old* project.

<img width="659" alt="Screenshot 2022-02-04 131050" src="https://user-images.githubusercontent.com/10340167/152580975-1073b5e7-8712-4c89-a3b0-9166993ecfe3.png">

I think it would be less confusing if it didn't appear in the top bad next to the GitHub link, and had some kind of notation that it is linking to the old project.

**Comment by matthewoestreich** [comment]
yea that's a good point. I'll get this removed ASAP.
