### ISSUE TITLE
Incorrect documented Prop names

### ISSUE THREAD

**Issue by johnthagen** [material-table-core/website#18]
The website says: https://material-table-core.com/docs/api/props/mt_prop_onChangeRowsPerPage

But the real name is `onRowsPerPageChange`. There are others incorrect as well. See:

- https://github.com/material-table-core/core/pull/263
- https://github.com/material-table-core/core/commit/ef81cb736e6224a4a9190ceb176d7398ce7171cd

**Comment by matthewoestreich** [comment]
thanks for this!

**Comment by Domino987** [comment]
Fixed, thank you!
